//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbContextSettings
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoginMaster()
        {
            this.UserProfileMasters = new HashSet<UserProfileMaster>();
        }
    
        public System.Guid LoginMasterId { get; set; }
        public string UserName { get; set; }
        public string LoginPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserProfileMaster> UserProfileMasters { get; set; }
    }
}
