//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DbContextSettings
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileMaster
    {
        public System.Guid UserProfileId { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PrimaryEmail { get; set; }
        public string RecoveryEmail { get; set; }
        public string MobileNumber { get; set; }
        public System.Guid LoginUserId { get; set; }
    
        public virtual LoginMaster LoginMaster { get; set; }
    }
}
